version: "3"

services:

  lorraine:
    image: container_day_lorraine:latest
    ports:
      - 8080:8080
    depends_on: [database]

  database:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
